In [ ]:
# Homework 6 Template
# G. Besla & R. Li

In [3]:
# import modules
import numpy as np
import astropy.units as u
from astropy.constants import G

# import plotting modules
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

# my modules
from ReadFile import Read
# Step 1: modify CenterOfMass so that COM_P now takes a parameter specifying 
# by how much to decrease RMAX instead of a factor of 2
from CenterOfMass2 import CenterOfMass



In [76]:
def OrbitCOM(galaxy,start,end,n):
    """function that loops over all the desired snapshots to compute the COM pos and vel as a function of time.
    inputs:
          galaxy - name of galaxy (MW,M31,M33)
          start - first snapshot to be read in
          end - last snapshot to be read in
          n - an integer indicating the intervals over which COM will be returned
    returns: 
          file containing COM position and velocity vectors as a function of time
    """
    
    # compose the filename for output
    fileout = 'Orbit_' + "%s"%(galaxy) + '.txt' 
    
    #  set tolerance and VolDec for calculating COM_P in CenterOfMass
    delta = 0.1
    if (galaxy != 'M33'):
        VolDec = 2
    # for M33 that is stripped more, use different values for VolDec
    else: 
        VolDec = 4
    
    # generate the snapshot id sequence 
    snap_ids = np.arange(start,end+1,n) # end+1 ensures last member of array is actually snap number for end
    # it is always a good idea to also check if the input is eligible (not required)
    if (len(snap_ids)==0):
        print("Start and end inputs are not valid")
        return
    
    # initialize the array for orbital info: t, x, y, z, vx, vy, vz of COM
    orbit = np.zeros([len(snap_ids),7])
    
    # a for loop 
    for  i,snap_id in enumerate(snap_ids): # loop over files
        
        # compose the data filename (be careful about the folder)
        ilbl = '000' + str(snap_id) # add a string of snap_id to value "000"
        ilbl = ilbl[-3:] # remove all but last 3 digits
        filename = "%s_"%(galaxy) + ilbl + '.txt' # create filename
        
        # Initialize an instance of CenterOfMass class, using disk particles
        COM = CenterOfMass(filename,1)
        # Store the COM pos and vel. Remember that now COM_P required VolDec
        COMP = COM.COM_P(delta,VolDec)
        COMV = COM.COM_V(COMP[0],COMP[1],COMP[2])
    
        # store the time, pos, vel in ith element of the orbit array,  without units (.value) 
        # note that you can store 
        # a[i] = var1, *tuple(array1)
        orbit[i] = (COM.time).value/1000, *tuple(COMP.value), *tuple(COMV.value)
        
        # print snap_id to see the progress
        print(snap_id)
        
    # write the data to a file
    # we do this because we don't want to have to repeat this process 
    # this code should only have to be called once per galaxy.
    np.savetxt(fileout, orbit, fmt = "%11.3f"*7, comments='#',
               header="{:>10s}{:>11s}{:>11s}{:>11s}{:>11s}{:>11s}{:>11s}"\
                      .format('t', 'x', 'y', 'z', 'vx', 'vy', 'vz'))

In [78]:
# Recover the orbits and generate the COM files for each galaxy
# read in 800 snapshots in intervals of n=5
# Note: This might take a little while - test your code with a smaller number of snapshots first! 

OrbitCOM('MW',0,800,5)
OrbitCOM('M31',0,800,5)
OrbitCOM('M33',0,800,5)


0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100
105
110
115
120
125
130
135
140
145
150
155
160
165
170
175
180
185
190
195
200
205
210
215
220
225
230
235
240
245
250
255
260
265
270
275
280
285
290
295
300
305
310
315
320
325
330
335
340
345
350
355
360
365
370
375
380
385
390
395
400
405
410
415
420
425
430
435
440
445
450
455
460
465
470
475
480
485
490
495
500
505
510
515
520
525
530
535
540
545
550
555
560
565
570
575
580
585
590
595
600
605
610
615
620
625
630
635
640
645
650
655
660
665
670
675
680
685
690
695
700
705
710
715
720
725
730
735
740
745
750
755
760
765
770
775
780
785
790
795
800
0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100
105
110
115
120
125
130
135
140
145
150
155
160
165
170
175
180
185
190
195
200
205
210
215
220
225
230
235
240
245
250
255
260
265
270
275
280
285
290
295
300
305
310
315
320
325
330
335
340
345
350
355
360
365
370
375
380
385
390
395
400
405
410
415
420
425
430
435
440
445
450
455
460
465
470
475
480
485
490
495


In [80]:
# Read in the data files for the orbits of each galaxy that you just created
# headers:  t, x, y, z, vx, vy, vz
# using np.genfromtxt

MWdata = np.genfromtxt('Orbit_MW.txt',dtype=None,names=True)
M31data = np.genfromtxt('Orbit_M31.txt',dtype=None,names=True)
M33data = np.genfromtxt('Orbit_M33.txt',dtype=None,names=True)

In [99]:
# function to compute the magnitude of the difference between two vectors 
# You can use this function to return both the relative position and relative velocity for two 
# galaxies over the entire orbit  

def magdiff(ax,ay,az,bx,by,bz):
    return np.sqrt((ax-bx)**2+(ay-by)**2+(az-bz)**2)

In [12]:
# Determine the magnitude of the relative position and velocities 

# of MW and M31

# of M33 and M31


In [13]:
# Plot the Orbit of the galaxies 
#################################



In [14]:
# Plot the orbital velocities of the galaxies 
#################################


In [96]:
MWdata['x']


array([ -1.08,  -1.71,  -2.15,  -1.71,  -2.38,  -2.97,  -0.58,  -3.6 ,
        -3.96,  -3.51,  -4.14,  -5.05,  -5.53,  -6.12,  -6.46,  -5.46,
        -7.06,  -8.27,  -9.05,  -9.49, -10.48,  -8.19, -11.41, -12.11,
       -13.17, -13.6 , -15.71, -17.04, -18.36, -20.84, -21.76, -22.53,
       -23.99, -26.07, -27.2 , -28.87, -31.49, -33.11, -35.66, -37.03,
       -39.2 , -41.15, -43.9 , -46.09, -48.79, -50.94, -52.22, -55.33,
       -58.54, -61.67, -64.62, -67.77, -71.16, -74.02, -77.26, -78.91,
       -77.1 , -73.13, -68.66, -66.43, -56.08, -49.22, -44.7 , -41.32,
       -37.49, -33.41, -29.32, -25.34, -21.86, -18.75, -15.34, -12.95,
        -9.9 ,  -6.75,  -5.07,  -2.57,  -0.44,   2.36,   4.93,   6.75,
         8.47,   8.45,   2.83,  -1.06,  -5.11,  -4.33,   3.27,  13.63,
        20.92,  22.19,  25.04,  27.8 ,  31.62,  34.79,    nan,  40.51,
        43.03,    nan,  48.45,  51.39,  53.01,    nan,  57.83,  60.3 ,
        63.23,  65.55,  68.06,  70.04,  73.08,  75.54,  77.65,  80.98,
      

In [98]:
M31data['x']

array([-377.35, -373.5 , -366.24, -361.86, -358.07, -351.84, -346.61,
       -341.95, -336.53, -332.68, -326.76, -324.06, -319.41, -312.89,
       -307.15, -310.52, -307.87, -304.3 , -300.61, -297.13, -293.16,
       -273.14, -284.52, -264.19, -275.64, -269.84, -264.75, -259.41,
       -253.45, -248.15, -242.04, -236.48, -230.06, -224.12, -217.19,
       -211.14, -192.09, -198.18, -191.04, -184.73, -177.77, -171.33,
       -153.4 , -149.27, -149.79, -142.89, -135.14, -127.41, -119.67,
       -110.8 , -101.98,  -93.4 ,  -84.2 ,  -75.68,  -66.58,  -58.19,
        -53.96,  -50.92,  -49.66,  -49.07,  -47.09,  -46.28,  -45.62,
        -44.48,  -43.42,  -42.02,  -40.8 ,  -40.55,  -39.35,  -38.13,
        -36.72,  -34.94,  -33.68,  -32.07,  -29.55,  -27.47,  -24.96,
        -22.52,  -19.14,  -15.98,  -11.97,   -7.07,    1.45,   12.6 ,
           nan,   21.7 ,   21.49,   42.11,   19.09,     nan,   25.17,
         28.1 ,   32.56,   34.42,   37.8 ,   40.8 ,   43.  ,     nan,
         49.21,   50

In [97]:
dx = MWdata['x']-M31data['x']

In [94]:
dx

array([ 3.7627e+02,  3.7179e+02,  3.6409e+02,  3.6015e+02,  3.5569e+02,
        3.4887e+02,  3.4603e+02,  3.3835e+02,  3.3257e+02,  3.2917e+02,
        3.2262e+02,  3.1901e+02,  3.1388e+02,  3.0677e+02,  3.0069e+02,
        3.0506e+02,  3.0081e+02,  2.9603e+02,  2.9156e+02,  2.8764e+02,
        2.8268e+02,  2.6495e+02,  2.7311e+02,  2.5208e+02,  2.6247e+02,
        2.5624e+02,  2.4904e+02,  2.4237e+02,  2.3509e+02,  2.2731e+02,
        2.2028e+02,  2.1395e+02,  2.0607e+02,  1.9805e+02,  1.8999e+02,
        1.8227e+02,  1.6060e+02,  1.6507e+02,  1.5538e+02,  1.4770e+02,
        1.3857e+02,  1.3018e+02,  1.0950e+02,  1.0318e+02,  1.0100e+02,
        9.1950e+01,  8.2920e+01,  7.2080e+01,  6.1130e+01,  4.9130e+01,
        3.7360e+01,  2.5630e+01,  1.3040e+01,  1.6600e+00, -1.0680e+01,
       -2.0720e+01, -2.3140e+01, -2.2210e+01, -1.9000e+01, -1.7360e+01,
       -8.9900e+00, -2.9400e+00,  9.2000e-01,  3.1600e+00,  5.9300e+00,
        8.6100e+00,  1.1480e+01,  1.5210e+01,  1.7490e+01,  1.93